### ISSUE TITLE
pre-built appx

### ISSUE THREAD

**Issue by unixwitch** [agowa338/WSL-DistroLauncher-Alpine#16]
hello,

for systems without access to the Windows Store (e.g. Windows 10 LTSC, Windows Server) it would be helpful to provide a downloadable appx as a release asset.  the alternatives are a bit of a hassle: either extracting the appx from the store manually or building it locally.

i appreciate that most people are probably using WSL on the desktop, so this isn't a huge issue - more of a nice to have if it's not too much effort.

**Comment by agowa338** [comment]
Well they should have been there...
Apparently they were all flagged draft, could have sworn they were published strange....
https://github.com/agowa338/WSL-DistroLauncher-Alpine/releases
