### ISSUE TITLE
A question about reinstallation

### ISSUE THREAD

**Issue by redblue9771** [agowa338/WSL-DistroLauncher-Alpine#2]
Suppose I reinstall Windows now and want to continue using the old apline. How do I re-register and configure the distribution as the default?

**Comment by agowa338** [comment]
That's not possible (wsl has no export functionality), except you write your own warper and create your own root.tar.gz from the running wsl environment. Than just add a reference to your tar.gz and it will install your tar.gz-ed userland.
The executable is very easy. It just throws a tar.gz of the whole userland against a windows api and provides some initialization commands (`DistroLauncher/DistroSpecial.h`).

Alternatively, you could just reinstall everything by doing:
On the old pc:
```
apk info|sort > /mnt/c/Users/YOUR_USERNAME/WSL_Backup/installed-packages.txt
tar c -z -f '/mnt/c/Users/YOUR_USERNAME/WSL_Backup/backup-archive.tar.gz' /root
```
Copy the content of `/mnt/c/Users/YOUR_USERNAME/WSL_Backup` e. g. `C:\Users\YOUR_USERNAME\WSL_Backup` onto the same path on the new pc.
On the new pc:

1. Enable Windows subsystem for linux
2. Install Alpine WSL from the store
3. Restore your backup and reinstall all packages
```
apk add $(cat /mnt/c/Users/YOUR_USERNAME/WSL_Backup/installed-packages.txt)
tar x -z -C '/root' -f '/mnt/c/Users/YOUR_USERNAME/WSL_Backup/backup-archive.tar.gz'
```

From that it is clear, that WSL is not a replacement for a true Alpine/Linux computer. It is better to consider it as a mostly stateless tool for working with linux applications on windows. By doing so, you get docker like behaviour, but with the additional benefit of doing things like:
`cat /etc/passwd | grep root | clip.exe` (piping from linux commands to windows commands and from windows to linux applications.
Therefore one also has no problem of just `wslconfig.exe /u Alpine; Alpine.exe` (PowerShell) to get a new clean wsl environment.

**Comment by redblue9771** [comment]
> 这是不可能的（wsl 没有导出功能），除了你编写自己的 warper 并从正在运行的 wsl 环境创建自己的 root.tar.gz。不只是添加对 tar.gz 的引用，它将安装 tar.gz-ed 用户区。
> 可执行文件非常简单。它只是针对 windows api 抛出整个 userland 的 tar.gz 并提供一些初始化命令（`DistroLauncher/DistroSpecial.h`）。
> 
> 或者，您可以通过执行以下操作重新安装所有内容：
> 在旧 PC 上：
> 
> ```
> apk info|sort > /mnt/c/Users/YOUR_USERNAME/WSL_Backup/installed-packages.txt
> tar c -z -f '/mnt/c/Users/YOUR_USERNAME/WSL_Backup/backup-archive.tar.gz' /root
> ```
> 将`/mnt/c/Users/YOUR_USERNAME/WSL_Backup`例如内容复制`C:\Users\YOUR_USERNAME\WSL_Backup`到新 PC 上的相同路径上。
> 在新的电脑上：
> 
> 1. 为 Linux 启用 Windows 子系统
> 2. 从商店安装 Alpine WSL
> 3. 恢复备份并重新安装所有软件包
> 
> ```
> apk add $(cat /mnt/c/Users/YOUR_USERNAME/WSL_Backup/installed-packages.txt)
> tar x -z -C '/root' -f '/mnt/c/Users/YOUR_USERNAME/WSL_Backup/backup-archive.tar.gz'
> ```
> 很明显，WSL 并不是真正的 Alpine / Linux 计算机的替代品。最好将它视为在 Windows 上使用 Linux 应用程序的主要无状态工具。通过这样做，你可以获得类似于 docker 的行为，但还有以下方面的好处:( 
> `cat /etc/passwd | grep root | clip.exe`从 linux 命令到 windows 命令以及从 windows 到 linux 应用程序的管道。
> 因此，只有`wslconfig.exe /u Alpine; Alpine.exe`（PowerShell）获得新的一个也没有问题干净的 wsl 环境。


Thank you for everything!
