### ISSUE TITLE
WslRegisterDistribution failed with error: 0x80070005

### ISSUE THREAD

**Issue by oritromax** [agowa338/WSL-DistroLauncher-Alpine#22]
![image](https://user-images.githubusercontent.com/2173554/83527028-12632e80-a509-11ea-8790-497532c3b49d.png)

While trying to install it from Windows Store, the error in the aforementioned image appears. 

I tried both normally and with elevated permission. 

Windows 10 2004 Build 19041

**Comment by agowa338** [comment]
Please try to disable the WSL (+ Hyper-V if you use that) feature, reboot, re-enable it, reboot and try again. 
I've seen this error before last time it was caused by a windows update.

**Comment by airtonix** [comment]
> Please try to disable the WSL (+ Hyper-V if you use that) feature, reboot, re-enable it, reboot and try again.
> I've seen this error before last time it was caused by a windows update.

For the rest of us mere mortals can you translate that into steps that we can follow?

**Comment by agowa338** [comment]
@airtonix There is a bug in some version of windows involving windows update breaking that feature.

That's:

> Please try to 
> 1. disable the WSL (+ Hyper-V if you use that) feature
> 2. reboot
> 3. re-enable it
> 4. reboot
> 5. and try again.
