### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by duxbuse** [agowa338/WSL-DistroLauncher-Alpine#24]
I just installed this in wsl1
And it makes me a user, but that user doesn't have the rights to run apk.

```bash
DESKTOP-DLHGUJ6:/mnt/c/Users/Sean/Documents/VSCODE$ apk update
ERROR: Unable to lock database: Permission denied    
ERROR: Failed to open apk database: Permission denied
```

Its annoying to have to su all the time. Is there a way to make the default user it creates have more permissions?
I googled it but could seem to make it work.

**Comment by agowa338** [comment]
You could install and configure sudo for password less elevation of apk.
Or you run `alpine.exe config --default-user root` to always use the root user, but keep in mind that some applications might not work as expected when executed as root.

**Comment by OctavioBR** [comment]
> Or you run alpine.exe config --default-user root to always use the root user, but keep in mind that some applications might not work as expected when executed as root.

I am considering this the best approach to my needs... Can you give an example of an application you know of that won't play nice if running as root?

**Comment by agowa338** [comment]
KDE gui applications for example refuse to start as root.
And I also have seen some console applications just printing a message to not run them as root and quit...

**Comment by Ayanmullick** [comment]
> You could install and configure sudo for password less elevation of apk.
> Or you run `alpine.exe config --default-user root` to always use the root user, but keep in mind that some applications might not work as expected when executed as root.

I was getting the same error trying to install PowerShell until I ran this and restarted.
https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.2#installation-via-direct-download---alpine-39-and-310
