### ISSUE TITLE
Bugfixing command failed but install succeeds

### ISSUE THREAD

**Issue by airtonix** [agowa338/WSL-DistroLauncher-Alpine#25]
```
Temporary directory: C:\Users\zenobius\AppData\Local\Temp\wsl_Alpine_setup
Downloading   : http://dl-cdn.alpinelinux.org/alpine/v3.9/releases/x86_64/alpine-minirootfs-3.9.0-x86_64.tar.gz
To local file : install.tar.gz
The current working directory is: C:\Users\zenobius\AppData\Local\Temp\wsl_Alpine_setup
File successfully deleted
Mime type available
Begin download
Cache filename available
100% [====================]
End download
Downloaded OK
Hash of file install.tar.gz is: f82efed1a80c9af86c38bed10f3541c5588453b97684d767a5a3b0f3fa0e3f09

Verifying Hash: OK
Installing, this may take a few minutes...
Executing bugfixing command: /bin/chmod 755 /
Executing bugfixing command: /sbin/apk --no-cache add shadow
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:
  shadow (missing):
    required by: world[shadow]
Bugfixing command failed.


==== MANUAL STEP ====
If you're on Windows 10 1803 17134, manually execute this/these command(s), NOW:
Or upgrade to the latest version of windows 10
/bin/chmod 755 /
/sbin/apk --no-cache add shadow
/bin/sed -i 's/^export PATH/#export PATH/' /etc/profile

Also you need to provide a /bin/bash executable to use bash.exe from Windows.
Either by symlinking any other shell to /bin/bash or by installing bash.
If you want to change the default user (after you created one), run:
Alpine.exe /config --default-user <username>
== // MANUAL STEP // ==
Installation successful!
```

**Comment by airtonix** [comment]
additionally, I can not use apk to update or install anything.

**Comment by agowa338** [comment]
Your wsl doesn't have internet access for some reason.
You could try to run `echo nameserver 1.1.1.1 > /etc/resolve.conf` if starts working after that, your dns server within wsl is either broken or firewalled off.

**Comment by airtonix** [comment]
It' actually to do with the recent hilarity around windows update and docker-desktop releasing a fatal update that completely borks the underlying networking stack.

I get around this using this powershell script: 

```
echo "Restarting WSL Service"
Restart-Service LxssManager
echo "Restarting Host Network Service"
Stop-Service -name "hns"
Start-Service -name "hns"
echo "Restarting Hyper-V adapters"
Get-NetAdapter -IncludeHidden | Where-Object `
    {$_.InterfaceDescription.StartsWith('Hyper-V Virtual Switch Extension Adapter')} `
    | Disable-NetAdapter -Confirm:$False
Get-NetAdapter -IncludeHidden | Where-Object `
    {$_.InterfaceDescription.StartsWith('Hyper-V Virtual Switch Extension Adapter')} `
    | Enable-NetAdapter -Confirm:$False
```

But unfortunately, by the time i discovered this i had already completely wiped my previous alpine install and am now facing the annoying scenario of having to setup from scratch a new linux OS. and am facing other annoying bugs.

... this is the reason why i moved to docker.

**Comment by dpalma9** [comment]
> Your wsl doesn't have internet access for some reason.
> You could try to run `echo nameserver 1.1.1.1 > /etc/resolve.conf` if starts working after that, your dns server within wsl is either broken or firewalled off.

Same issue and this solves it. 
Doesn't the default DNS should work? And why the default DNS works for everything else?

**Comment by agowa338** [comment]
> Doesn't the default DNS should work? And why the default DNS works for everything else?

It should, but the error is beyond the scope of this project than. Either you firewalled it off, an av is blocking it, you messed with the wsl virtual network, something in your windows installation is broken, ...

**Comment by dpalma9** [comment]
> It would be great, if you could debug this error a bit more,

Do you know how can I debug it more? Because I have not a clue how to start testing things that can show me the error better.
