### ISSUE TITLE
Not enough rights for default user created

### ISSUE THREAD

**Issue by oxijas** [agowa338/WSL-DistroLauncher-Alpine#30]
During installation a new user is created. The readme says that this user is added to adm & wheel group etc. 
However when I start wsl I do not have enough rights to do basic things like apk update. The password of the root user is unknown. How do I get in?

**Comment by eschen42** [comment]
@oxijas Please include a comment about how to get `apk update` to run.  I get
```
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied
```
even though `myuser` is member of `adm` and `wheel`
