### ISSUE TITLE
Upgrade to 3.13 without waiting for MS Store update?

### ISSUE THREAD

**Issue by Zegnat** [agowa338/WSL-DistroLauncher-Alpine#35]
Currently the Alpine version shipped [on the Microsoft Store](https://www.microsoft.com/store/productId/9P804CRF0395) is on 3.12.1. Not only is that 3 patch versions out of date, a v3.13 branch has been around for 2 months now.

This repository seems to be up-to-date, updating its internal files to get the latest 3.13 patch barely a day after official release. But the store page has not been updated at all.

Is there a way to update the Alpine version in my WSL without waiting for the packaged version in the store to be updated? Preferably without setting up a C++ building environment.

If not, let this issue be a friendly nudge to update the Microsoft Store distribution. I would like to grab some packages currently shipped only in the 3.13 repository without risking them requiring something 3.12 cannot support. Thanks for the hard work!

**Comment by agowa338** [comment]
> Is there a way to update the Alpine version in my WSL

It's simple just run the normal update command using apk. Apk will take care of updating all packages to the latest version.
The only requirement for the alpine launcher is that bootstraps *an* alpine Linux environment. Everything else (like upgrading versions) can be done from within the wsl environment.

Updating the version within the launcher will also only take effect for new setups or if one deletes (aka. `wslconfig /t`) the local wsl distribution first.

**Comment by Zegnat** [comment]
Ah, hmm, interesting.

I updated `/etc/apk/repositories` as per [the Alpine wiki](https://wiki.alpinelinux.org/wiki/Upgrading_Alpine#Upgrading_to_latest_release) and did a full upgrade, followed by `sync`. But never got `/etc/alpine-release` to change, so I was thinking something about the Alpine core / kernel was being kept back.

What would be the recommended way to check that the Alpine environment was actually updated internally? 🤔

**Comment by dougbreaux** [comment]
Heh, just wondering the exact same thing.

**Comment by benjarrell** [comment]
> 
> 
> Ah, hmm, interesting.
> 
> I updated `/etc/apk/repositories` as per [the Alpine wiki](https://wiki.alpinelinux.org/wiki/Upgrading_Alpine#Upgrading_to_latest_release) and did a full upgrade, followed by `sync`. But never got `/etc/alpine-release` to change, so I was thinking something about the Alpine core / kernel was being kept back.
> 
> What would be the recommended way to check that the Alpine environment was actually updated internally? 🤔

You need to install the [`alpine-base`](https://pkgs.alpinelinux.org/contents?branch=v3.13&name=alpine-base&arch=x86_64&repo=main) package for those files.

**Comment by slycordinator** [comment]
It's also of note that sometimes when you install the alpine-base package, the files `/etc/alpine-release` and `/etc/issue` get left alone. Instead, it updates/creates files called `/etc/alpine-release.apk-new` and `/etc/issue.apk-new`
