### ISSUE TITLE
WSLRegDistro Failed

### ISSUE THREAD

**Issue by F9Alejandro** [agowa338/WSL-DistroLauncher-Alpine#38]
Took a look at it in dmesg to see what is actaully failing.
```
[    1.764575] EXT4-fs (sdb): mounted filesystem with ordered data mode. Opts: discard,errors=remount-ro,data=ordered
[    1.816979] init: (1) ERROR: ConfigApplyWindowsLibPath:2402: open /etc/ld.so.conf.d/ld.wsl.conf
[    1.816987]  failed 2
[    1.825387] init: (2) ERROR: UtilCreateProcessAndWait:636: /bin/mount failed with 8
[    1.826027] init: (1) ERROR: UtilCreateProcessAndWait:656: /bin/mount failed with status 0x
[    1.826031] ff00
[    1.826049] init: (1) ERROR: ConfigMountFsTab:2457: Processing fstab with mount -a failed.
[    1.830380] init: (3) ERROR: UtilCreateProcessAndWait:636: /bin/mount failed with 8
[    1.831004] init: (1) ERROR: UtilCreateProcessAndWait:656: /bin/mount failed with status 0x
[    1.831008] ff00
[    1.837920] WARNING: /usr/share/zoneinfo/America/New_York not found. Is the tzdata package installed?
[    1.862365] init: (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\WINDOWS\system32

[    1.862612] init: (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\WINDOWS
[    1.862815] init: (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\WINDOWS\System32\Wbem

[    1.863021] init: (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\WINDOWS\System32\WindowsPowerShell\v1.0\

[    1.863297] init: (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\WINDOWS\System32\OpenSSH\

[    1.863509] init: (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files\Microsoft VS Code\bin

[    1.863720] init: (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Users\Bytor\AppData\Local\Programs\Python\Python39\Scripts\

[    1.863925] init: (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Users\Bytor\AppData\Local\Programs\Python\Python39\

[    1.864129] init: (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Users\Bytor\AppData\Local\Microsoft\WindowsApps

[    1.867360] init: (9) ERROR: CreateProcessEntryCommon:606: execvpe /bin/ash failed 8
[    1.867369] init: (9) ERROR: CreateProcessEntryCommon:616: Create process not expected to return
[   13.946328] blk_update_request: I/O error, dev sdb, sector 0 op 0x1:(WRITE) flags 0x800 phys_seg 0 prio class 0
[   13.947488] sd 0:0:0:1: [sdb] Synchronizing SCSI cache
[   13.985665] Buffer I/O error on dev sdb, logical block 33521664, lost sync page write
[   13.985669] JBD2: Error -5 detected when updating journal superblock for sdb-8.
[   13.985669] Aborting journal on device sdb-8.
[   13.985670] Buffer I/O error on dev sdb, logical block 33521664, lost sync page write
[   13.985671] JBD2: Error -5 detected when updating journal superblock for sdb-8.
[   41.873601] scsi 0:0:0:1: Direct-Access     Msft     Virtual Disk     1.0  PQ: 0 ANSI: 5
[   41.874447] sd 0:0:0:1: Attached scsi generic sg1 type 0
[   41.876126] sd 0:0:0:1: [sdb] 536870912 512-byte logical blocks: (275 GB/256 GiB)
[   41.876132] sd 0:0:0:1: [sdb] 4096-byte physical blocks
[   41.876409] sd 0:0:0:1: [sdb] Write Protect is off
[   41.876414] sd 0:0:0:1: [sdb] Mode Sense: 0f 00 00 00
[   41.876876] sd 0:0:0:1: [sdb] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[   41.883473] sd 0:0:0:1: [sdb] Attached SCSI disk
[   41.896195] EXT4-fs (sdb): mounted filesystem with ordered data mode. Opts: discard,errors=remount-ro,data=ordered
```
found this. Says it mounted but had loads of errors with access and locations in the fs.
Is there a workaround for this. give Error of access denied.

Fixed. Got a mini rootfs from alpine linux site for my arch and it seems to work just fine after manual mount/import. using alpine.exe after works as expected.

**Comment by agowa338** [comment]
I'm just calling the windows api. I cannot change how the windows API performs the import.
And if you say that manually importing it works, that's just more strange, as this application is just downloading the tar.gz from alpine linux and throwing it against the windows api (without any preprocessing).
Currently the only thing that I found out is that this api starts to work again if one uninstalls reboots and reinstalls hyper-v, container, Hypervisor Platform and wsl.

Can you provide what exactly you did to manually import?

**Comment by F9Alejandro** [comment]
So the work around based on what I found from the command `wsl dmesg` is that it looks that the image downloaded is either corrupt or incompatible with wsl at least on my system it was or the specific version downloaded did.

What I downloaded and used was mini rootfs from alpine linux website for my specific arch type (in this case arm64/aarch64) and used the location in appdata/local/packages/(alpine app location)/LocalState/ for the mount point of the drive and the install path (location of tar.gz) from where ever the mini rootfs was located (in this case downloads).

Doing it this way ensured that it was still compatible with the windows UWP app for alpine and can still access and change as needed without having to rebuild from scratch. Again `wsl dmesg` is your friend it gives you loads of insight into what is going on.

**Comment by agowa338** [comment]
It's verry unlikely that the downloaded file is corrupted.
We would have to reliably hit a sha256 hash collision for this to occur...

Also the mini rootfs is the same image that this application uses.

> arm64/aarch64

I currently don't support this as I cannot test for this platform.

And the hardcoding of the x86_64 url is intentional as checking the GPG signature via C++ is quite complicated and therefore the simplest solution to guarantee a similar level of security is to check the sha256 hash.
(Also the launcher is currently compiled as x86_64 only, so I'm a bit surprised that the launcher works on arm64).
