### ISSUE TITLE
License for checksum functions?

### ISSUE THREAD

**Issue by 3xtant** [agowa338/WSL-DistroLauncher-Alpine#39]
Hi, thanks for this project. To me, this is the best WSL-DistroLauncher fork. Great job.

My question is: what is the license of the Checksum Verify functions? I'd like to add them to my fork, but there is no license or copyright info.

Thanks!

**Comment by agowa338** [comment]
I wrote it myself so it's MIT.

It's based upon the windows crypto api documentation and examples from docs.microsoft.com and some stackoverflow for things like string conversions...
docs.microsoft.com used MD5 I rewrote it for sha256.
The md5 version is here: https://docs.microsoft.com/en-us/windows/win32/seccrypto/example-c-program--creating-an-md-5-hash-from-file-content
