### ISSUE TITLE
Missing core package `alpine-base` from freshly-installed Alpine distro

### ISSUE THREAD

**Issue by josh-berry** [agowa338/WSL-DistroLauncher-Alpine#41]
The `alpine-base` package and its dependencies seem to be missing from a freshly-installed Alpine distro, meaning some common things like `lbu` are missing, and files like `/etc/alpine-release` aren't updated correctly after upgrading to a newer Alpine version.

**Comment by agowa338** [comment]
That's an upstream issue then. This package uses the official userland.
I'll consider adding alpine-base within the first run script though. Thanks for pointing it out.
