### ISSUE TITLE
0x80070005 Access is denied (download was from store, then "Launch")

### ISSUE THREAD

**Issue by Amondale** [agowa338/WSL-DistroLauncher-Alpine#42]
Downloading   : https://dl-cdn.alpinelinux.org/alpine/v3.13/releases/x86_64/alpine-minirootfs-3.13.4-x86_64.tar.gz
To local file : install.tar.gz
The current working directory is: C:\Users\almo\AppData\Local\Temp\wsl_Alpine_setup
File successfully deleted
Mime type available
Begin download
Cache filename available
100% [====================]
End download
Downloaded OK
Hash of file install.tar.gz is: 8e21c85c4a5bb406180136aa03f814c56ffc7498ba7886c5ea13fec92d528ead

Verifying Hash: OK
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070005
WslRegisterDistribution failed
Error: 0x80070005 Access is denied.

Press any key to continue...

**Comment by Amondale** [comment]
https://github.com/microsoft/WSL/issues/6744#issuecomment-890377812 seemed to clear it up. Any idea why the "Launch" button in store isn't running the command window Elevated?

**Comment by agowa338** [comment]
Because it should work without elevation. This is an issue in the underlying windows api...
