### ISSUE TITLE
'Alpine WSL Support' hyperlink on Windows 10's  Microsoft Store app page is not useful.

### ISSUE THREAD

**Issue by 62f** [agowa338/WSL-DistroLauncher-Alpine#43]
![WSL](https://user-images.githubusercontent.com/68332197/131162516-3bd27fdf-859a-4af4-a0eb-d08222d063f4.png)

**Comment by agowa338** [comment]
That button only has an email address behind it. In fact, it is there because Microsoft requested it in order to approve the app.
But until now I only received scam, phishing, and spam emails on that address...
