### ISSUE TITLE
Alpine install fail

### ISSUE THREAD

**Issue by ruipach** [agowa338/WSL-DistroLauncher-Alpine#5]
PS C:\Users\username> systeminfo | Select-String "^OS Name","^OS Version"

OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.16299 N/A Build 16299

---

C:\Windows\System32>Alpine.exe install
Temporary directory: C:\Users\username\AppData\Local\Temp\wsl_Alpine_setup
Downloading   : http://dl-cdn.alpinelinux.org/alpine/v3.9/releases/x86_64/alpine-minirootfs-3.9.0-x86_64.tar.gz
To local file : install.tar.gz
The current working directory is: C:\Users\username\AppData\Local\Temp\wsl_Alpine_setup
File successfully deleted
Mime type available
Begin download
Cache filename available
100% [====================]
End download
Downloaded OK
Hash of file install.tar.gz is: f82efed1a80c9af86c38bed10f3541c5588453b97684d767a5a3b0f3fa0e3f09

Verifying Hash: OK
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x8007007b
WslRegisterDistribution failed
Error: 0x8007007b The filename, directory name, or volume label syntax is incorrect.

**Comment by agowa338** [comment]
Please check your dns.

**Comment by ruipach** [comment]
Hi, should check dns against which host? Files are being download fine from alpine linux cdn.
Additional information, I am using a proxy, could this be the reason?

**Comment by agowa338** [comment]
There was a problem with network not being correctly recognized by wsl, so please disconnect wifi and reconnect it than reopen alpine wsl and try again.

Also if you use hyper-v and performed a system upgrade (one of the mayore windows 10 updates semi annually) recently, disable the hyper-v feature restart the pc and than reenable it and boot again.

**Comment by ruipach** [comment]
OK, thanks.
Installed debian without any issue with the same conditions (as alpine failed) so I would ne expect that this issue is due to wsl.
Will give a try and feedback.

**Comment by ruipach** [comment]
Hi, still not working even using the ethernet cable. As said, debian installed with this same conditions.
Let me know if you want to check any detail in the process that I can supply you for investigation.

**Comment by agowa338** [comment]
As you're using the Enterprise Version, you're not a windows developer by change? Having a step trace would help to debug this issue.
Otherwise I've to I find a download for the Enterprise Version, first. I'm testing with the latest and the latest insider Version.

**Comment by ruipach** [comment]
Sure. Could you please share a simple guide to collect the required step trace?

**Comment by agowa338** [comment]
Not really simple, but...

1. You need Visual Studio
2. You have to import this project
3. Set a breakpoint right after the file download.
3. Delete the local wsl environment `wslconfig /u Alpine` (deletes all files within the Alpine Linux environment)
4. Start alpine and quickly attach visualstudio to the remote process, before it finished downloading the userland.
5. Your breakpoint should now be hit and the process should pause.
6. Single/Procedure step through the code until you get the error, most likely somewhere within WslApiLoader.cpp
