### ISSUE TITLE
install apache

### ISSUE THREAD

**Issue by nativecode2020** [agowa338/WSL-DistroLauncher-Alpine#50]
I need to install apache on it, so when I do "apk update "   
I have this message 
```
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied
```

when I change to root by su root need a password i don't know what is the default password

**Comment by agowa** [comment]
You set the root password on first run. It should have prompted you for it. But as it's wsl you can go around the auth system by running `wsl.exe -d Alpine -u root`
