### ISSUE TITLE
Can an exe copy be provided here on github plz thx! 

### ISSUE THREAD

**Issue by OZZlE** [agowa338/WSL-DistroLauncher-Alpine#53]
My company has blocked microsoft store because you can install anything I guess and they don't allow that.

We as devs are admins however and can install with installers. Could they be uploaded here as well? thanks!

**Comment by agowa** [comment]
I thought I did, but somehow GitHub being GitHub the releases were all unpublished and marked as drafts somehow...
I re-published them now.

Look here: https://github.com/agowa/WSL-DistroLauncher-Alpine/releases


Also just fyi you don't need the launcher anymore. In recent versions of windows you can just import the tar.gz archives directly using wsl.exe
