### ISSUE TITLE
This Certificate has expired

### ISSUE THREAD

**Issue by tinnnysu** [agowa338/WSL-DistroLauncher-Alpine#6]
Cert vaild from 4/28/2018 to 4/29/2019 form release page

**Comment by scrouthtv** [comment]
Certificate has expired & I think the current release does not support wsl 2

**Comment by agowa338** [comment]
There is a new test signature on the new release. The releases here originally were only intended for testing and for cases where the windows store could not be used.

There will not be a wls 2 supporting release from my side.
